### ISSUE TITLE
Performance Issues on Android

### ISSUE THREAD

**Issue by srz2** [RNCryptor/JNCryptor#23]
So I am trying to use this for android and it works but the performance is terrible. It takes several seconds to decrypt an asset I have.

For instance, I have images as low as 50KB to 150KB so nothing too large. But whenever I try to decrypt them, it takes several seconds for them to process. I use this for iOS and it's nearly instantaneous. Would anyone have any suggestions? The function I am using for this process is below...

public byte[] decryptInputStream(InputStream in){
        if(in == null)
            return null;

```
    ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
    byte[] buffer = new byte[1024];
    int i = Integer.MAX_VALUE;
    try{
        while((i = in.read(buffer, 0, buffer.length)) > 0)
            outputStream.write(buffer, 0, i);
    }
    catch(Exception e){

    }
    try {
        byte[] decrpytedStream = decryptor.decryptData(outputStream.toByteArray(), KEY.toCharArray());
        return decrpytedStream;
    }
    catch(CryptorException e){
        Log.e("AES Cryptor", "Input Stream Decryption Error");
    }
    return null;
}
```

**Comment by SemihAkar** [comment]
+1

**Comment by pallavivprasad** [comment]
I tried this library, but as the above comments say, it is very slow, for encryption it takes around 9 seconds and for decryption it takes 3-4 secs. how can it be made faster?

**Comment by dmjones500** [comment]
@pallavivprasad There isn't really any way to speed it up - this seems to be how long Java takes to perform this operation on Android. I suspect the only solution is to write something native and access it via NDK or similar. I don't have the time to address that currently, but if someone wants to suggest a patch, it would be very welcome.

In general, I think there needs to be a fork for this project for Android. That fork can address this issue, plus other Android-specific problems, like #25.

**Comment by wangbourne** [comment]
+1, performance improvement is required :)

**Comment by cguess** [comment]
I did some tracing and the issue seems to be in the java.security.MessageDigest.digest call that takes place within the PKCS5S2 generation call in the BouncyCastle library. So yes, it seems to be a problem with the Java implementation itself.

Since this library is Java-agnostic it probably wouldn't be a great idea to monkey-patch anything in.

**Comment by msgrasser** [comment]
Just wanted to give an update in case anyone else comes across this - RNCryptor officially has mentioned in a couple of places that this is a performance issue with the java library being used on Android, and has called for a JNI solution.

In doing some digging over the weekend, I came across [this library](https://github.com/TGIO/RNCryptorNative) which has accomplished that. The benchmarking in the README there seems to confirm that the JNI method reduces much of the latency in both encryption and decryption. Worth checking out, and perhaps working into the official RNCryptor arsenal...

**Comment by rnapier** [comment]
@msgrasser Thanks for the reminder again; I keep meaning to bring that one "into the fold." I haven't done an extensive review of it, but it looks very solid.

**Comment by msgrasser** [comment]
@rnapier Great! 

I only mentioned it here because I started implementing a JNI for RNCryptor myself and had [stupidly] put in a couple of hours before a lightbulb went off saying "Well since Rob suggested this formally in the JNCryptor README, there _must_ be someone else working on it." As a bonus, the one above has some cool features like "decodeAsync" with callbacks too, optionally saving a bit of time on implementing threading, etc. Just wanted to link to it somewhere within this project so people could come across it before [stupidly] spending time on starting from scratch like I did.

Anyway, thank you so very much for the awesome set of libs - they are a much appreciated gift to the world of secure data storage/transmission!!!

**Comment by hoanghiephui** [comment]
Do not know if you can build a version native for android?

**Comment by rnapier** [comment]
@hoanghiephui, please see https://github.com/TGIO/RNCryptorNative, referenced earlier in this thread.

**Comment by hoanghiephui** [comment]
@rnapier Oh! Thanks a lot, I tried, but apparently it does not work well. I am using your library for the ios, the data sent to the android, it has not been decoded.

**Comment by rnapier** [comment]
@hoanghiephui I don't understand the question. RNCryptorNative should be completely compatible with the other RNCryptor implementations.

**Comment by hoanghiephui** [comment]
I'm having a problem, when data is encrypted by android lib rncryptornative. It fails to decrypt on ios (using same passcode)

And seems like test vectors wasn't processed, I think there're things that aren't running properly with your algorithm. I hope you could spend some time to help it works better

**Comment by rnapier** [comment]
If you believe a test vector is failing in TGIO/RNCryptorNative, you should definitely open an issue there with the vector that's failing. The vast majority of the time when a message fails to decrypt its because you did not send precisely the same message (byte for byte) to the decryptor that you got from the encryptor. It is almost always an encoding problem, not a crypto problem. That said, it is possible that RNCryptorNative has some bug, but you would need to open an issue there with a failing case (the JNCryptor issue board can't really help you).

**Comment by hoanghiephui** [comment]
Ok, Thanks a lot!

**Comment by babulpatel1309** [comment]
For too slow decryption and encryption here is the perfect solution.

[https://github.com/TGIO/RNCryptorNative?utm_source=android-arsenal.com&utm_medium=referral&utm_campaign=3643)](https://github.com/TGIO/RNCryptorNative?utm_source=android-arsenal.com&utm_medium=referral&utm_campaign=3643)

found this library while i was searching for alternatives of JNCryptor. This lib derived from native and it does pretty well job.
I had tried many solution but none of that was working and finally this library did. 

You can check the compare graph below.

![1](https://user-images.githubusercontent.com/7448808/29955838-3d08132a-8f00-11e7-9837-c5ccbbe0abbd.png)



![25](https://user-images.githubusercontent.com/7448808/29955837-3bbba702-8f00-11e7-94a7-e1307bf6eb15.png)

**Comment by dmjones500** [comment]
@babulpatel1309 Thanks for the pointer. However, please don't spam this message over any more issues, thanks. This is the right place to put it.

**Comment by vijayendra-tripathi** [comment]
I haven't tested this personally but from what I know after introduction of ART in Android Nougat, the system turns byte code into native and thus performance of this library must have improved a lot. Android Nougat was launched sometime in August 2016 and most of the comments here are before or just around this time. The benchmark used by @babulpatel1309 in 2017 looks interesting but I am not sure what OS version and device was used for comparison. I will try on the newer versions and see how it works.
