### ISSUE TITLE
AES128 and JCEUnlimitedPolicy

### ISSUE THREAD

**Issue by hiworld75018** [RNCryptor/JNCryptor#29]
Is it possible to have something like a 'AES128JNCryptor' class, with AES_128_KEY_SIZE, in the package - so users can use the standard JRE without installing JCEUnlimitedPolicy ? This would be nice, and can be used with some kRNCryptorAES128Settings (with keySize = kCCKeySizeAES128) on the iOS side.

Thansk.

**Comment by rnapier** [comment]
Note that this will no longer work with the iOS implementation. The latest release no longer is configurable in this way. Making it quasi-configurable was a mistake in the original API, because the format does not encode any of those settings.

It is not too difficult to create an equivalent custom-decryptor in Swift, but it won't work out to the box. Note that this will break compatibility with all other implementations as well.

**Comment by hiworld75018** [comment]
Thanks for your quick answer. I find your work really interesting, because it is usable on both the server and client sides.

I can witness that most server installs use the stock Java (without JCEUnlimitedPolicy), and AES128 is sufficient for most cases. Moreover, I still use Obj-C because of iOS 6 compatibility. Is it possible to make the system work with stock AES128 "out of the box" somehow ?

**Comment by rnapier** [comment]
Not without modifying the data format. There is a plan underway to upgrade it and provide a security-reducing option (reduction of PDKBDF2 iterations for JavaScript). There's been one other request for 128-bit AES keys, in order to work with micro-controllers in C, and one of my security reviewers also mentioned this as a desirable option, so I'll add it to the v4 spec. But I don't expect a v4 reference implementation (Swift) before the end of the year, with the other implementations (like this one) following along later. I don't know how committed @dmjones500 is to updating the Java implementation or if someone else will pick it up (or if I'll need to do it, though I'm not really a Java programmer).

If you don't need any interoperability beyond your own implementations, my recommendation would be to just fork and modify the code to use the configuration you want. That's how people have been handling modifying PBKDF2 iterations.

**Comment by hiworld75018** [comment]
Great news. I really think that different options, with AES128 as the "base line", is the way to go. If I have some spare time, I would be happy to lend you a hand on the java side - or even on the Obj-C. At the moment, for my requirements, I am studying the fork option.

**Comment by dmjones500** [comment]
@rnapier I've been rather absent of late, although this is partly because the non-Android parts of this project are done and thus dormant.

If we opt to move to a different spec, I'll make an update.

For the record, I don't think we should default to AES-128 just because Java makes it mildly difficult to use 256 bit crypto.
