### ISSUE TITLE
Different encryption on IOS and android.

### ISSUE THREAD

**Issue by CDNRahulSonpaliya** [RNCryptor/JNCryptor#39]
Hello,

I am using this library in my android project and https://github.com/Gurpartap/aescrypt in ios project. I am encrypting same text with same encryption key, but it is giving me different results on ios and android.

**Comment by rnapier** [comment]
Every encryption via RNCryptor will return a unique output (not just across platforms; if you encrypted twice on the same platform you will get different results). That is by design and is a significant security requirement. There are random numbers included in the format to cause this to happen.

That said, looking at AESCrypt, it doesn't appear to implement the RNCryptor format at all, so you wouldn't expect them to match. The AESCrypt format appears to use a very weak KDF and includes no authentication, so I would not consider it a secure format.

If you're looking for an iOS implementation of RNCryptor, see the [RNCryptor](https://github.com/RNCryptor/RNCryptor) framework (Swift) or [RNCryptor-ObjC](https://github.com/RNCryptor/RNCyrptor-objc).
